data_ingestion:
  ticker: MSFT
  start_date: 2020-01-01
  end_date: 2024-12-31
  raw_data_path: artifacts/data_ingestion/data.csv

data_transformation:
  features:
    - ema
    - sma
    - rsi
    - macd
    - atr
    - bollinger
    - obv
    - vwap
    - price_position
    - lagged_returns
  train_test_split: 0.9
  lookback: 24
  horizon: 1
  include_ohlc: true
  X_preprocessor_path: artifacts/data_transformation/x_preprocessor_path.pkl
  y_preprocessor_path: artifacts/data_transformation/y_preprocessor_path.pkl

model_training:
  epochs: 20
  batch_size: 32
  model_save_path: artifacts/model_training/lstm.keras
  evaluations_save_path: artifacts/model_training/evaluations.json
  