data_ingestion:
  ticker: AAPL
  start_date: 2020-01-01
  end_date: 2024-12-31
  raw_data_path: artifacts/data_ingestion/data.csv

data_transformation:
  features:
    - ema
    - gkvol
    - vpt
  train_test_split: 0.9
  lookback: 24
  horizon: 1
  preprocessor_path: artifacts/data_transformation
  include_ohlc: true


model_trainer:
  