data_ingestion:
  source_path: notebooks/data/stock_data.csv
  raw_data_path: artifacts/data_ingestion/data.csv
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv

data_transformation:
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl

model_trainer:
  